### PR TITLE
Add wmi_exporter

### PR DESCRIPTION
**Pull request by MattMencel**
Requires Chocolatey package manager.

### CODE REVIEW

**Comment by viktorradnai** [comment]
I haven't got a good way to test this but it looks good. I'm merging it.

**Comment by viktorradnai** [comment]
@MattMencel Actually I do have an issue with this which wasn't immediately obvious. The whole cookbook now depends on chocolatey. Apparently there is a 'chocolatey_package' provider in Chef, is it possible to use that instead?

**Comment by MattMencel** [comment]
The chocolatey_package resource requires Chocolatey to be installed prior to use.

```Recipe: base-windows::packages
  * chocolatey_package[vmware-tools] action upgrade

    ================================================================================
    Error executing action `upgrade` on resource 'chocolatey_package[vmware-tools]'
    ================================================================================

    Chef::Exceptions::MissingLibrary
    --------------------------------
    Could not locate your Chocolatey install. To install chocolatey, we recommend
    the 'chocolatey' cookbook (https://github.com/chocolatey/chocolatey-cookbook).
    If Chocolatey is installed, ensure that the 'ChocolateyInstall' environment
    variable is correctly set. You can verify this with the PowerShell command
    '[System.Environment]::GetEnvironmentVariable('ChocolateyInstall', 'MACHINE')'.
```

I'm open to suggestions.  Should I expect the cookbook user to have Chocolatey installed prior to using this cookbook and just document it?

**Comment by viktorradnai** [comment]
The way I see this, we have four options in decreasing order of complexity:

1. Raise an RFC for conditional dependencies as suggested in the discussion in here: https://github.com/chef/chef/issues/1613 and here: http://tickets.opscode.com/browse/CHEF-3282 --  but which nobody actually did so far I think.
2. Break this cookbook into a Linux and a Windows specific one, only with collectors appropriate for each platform. 
3. Remove the dependency on the chocolatey cookbook and document that it's needed. Since the main goal of this cookbook is to provide custom resources rather than recipes that are directly usable, I think this is fine.
4. Force the dependency on the chocolatey cookbook which is a no-op on Linux but still every node has to download it.

I think out of all of these I would prefer option 3 and there is some agreement within the company from Chef/Windows users.

**Comment by MattMencel** [comment]
I updated my code and have a new PR for you.  I went with option 3 as you suggested.

**Pull request merged**
